'use strict';
// Stage bosses. Every BOSS_INTERVAL seconds of flying the ledges retract, creatures flee, a versus screen plays and
// the stage's boss attacks with its own weapons. Attacks and time drain its stamina; once it is tired
// the player finishes it with the equipped skin's fatality.
const BOSS_INTERVAL=300,FATALITY_TIME=2.8;
let boss=null,nextBossTime=BOSS_INTERVAL,bossBuf=null,rewardCoins=[],rewardSound=0;
const easeIn=k=>k*k,easeOut=k=>1-(1-k)*(1-k);

// ---------- Boss art (drawn around 0,0, roughly ±120 wide) ----------
function bossEye(px,py,r,o,color=INK){ctx.fillStyle='#fff';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(px,py,r,r*1.12,0,0,TAU);ctx.fill();ctx.stroke();
 if(o.tired){ctx.lineWidth=2.2;ctx.beginPath();for(let a=0;a<TAU*2.2;a+=.3){const rr=r*.08*a;ctx.lineTo(px+Math.cos(a+o.t*6)*rr,py+Math.sin(a+o.t*6)*rr)}ctx.stroke();return}
 const ex=px+o.lookX*r*.38,ey=py+o.lookY*r*.38;ctx.fillStyle=color;ctx.beginPath();ctx.arc(ex,ey,r*.5,0,TAU);ctx.fill();ctx.fillStyle=INK;ctx.beginPath();ctx.arc(ex,ey,r*.25,0,TAU);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ex-r*.16,ey-r*.18,r*.14,0,TAU);ctx.fill()}
function bossBrow(px,py,w,tilt,o){if(o.tired)tilt*=-.5;ctx.strokeStyle=INK;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(px-w,py-tilt*7);ctx.lineTo(px+w,py+tilt*7);ctx.stroke()}
function grimace(px,py,w,h,o,inner='#7a1030'){const hh=o.tired?h*.35:h*(.45+.55*o.attack),rad=Math.min(hh/2,10),n=Math.max(3,Math.round(w/7)),tw=w/n;ctx.fillStyle=inner;ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(px-w,py-hh/2,w*2,hh,rad);ctx.fill();ctx.fillStyle='#fff';
 for(let i=0;i<n;i++){const tx=px-w+(i+.5)*2*tw,d=Math.min(9,hh*.4);ctx.beginPath();ctx.moveTo(tx-tw*.85,py-hh/2);ctx.lineTo(tx,py-hh/2+d);ctx.lineTo(tx+tw*.85,py-hh/2);ctx.fill();ctx.beginPath();ctx.moveTo(tx-tw*.85,py+hh/2);ctx.lineTo(tx,py+hh/2-d);ctx.lineTo(tx+tw*.85,py+hh/2);ctx.fill()}
 ctx.beginPath();ctx.roundRect(px-w,py-hh/2,w*2,hh,rad);ctx.stroke()}
function crownShape(cy,w,h){ctx.fillStyle='#ffd23f';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-w,cy);ctx.lineTo(-w*1.15,cy-h);ctx.lineTo(-w*.55,cy-h*.5);ctx.lineTo(0,cy-h*1.2);ctx.lineTo(w*.55,cy-h*.5);ctx.lineTo(w*1.15,cy-h);ctx.lineTo(w,cy);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ff4d5e';ctx.beginPath();ctx.arc(0,cy-h*.45,w*.13,0,TAU);ctx.fill();ctx.fillStyle='#44d9ff';ctx.beginPath();ctx.arc(-w*.62,cy-h*.3,w*.09,0,TAU);ctx.arc(w*.62,cy-h*.3,w*.09,0,TAU);ctx.fill()}
function artStorm(o){const puffs=[[-72,8,40],[-34,-22,50],[22,-28,54],[70,2,42],[0,14,54],[-44,32,32],[46,30,34]];
 for(let k=0;k<3;k++){const a=o.t*1.6+k*TAU/3;ctx.save();ctx.translate(Math.cos(a)*114,Math.sin(a)*26+10);ctx.rotate(a);ctx.fillStyle='#ffe14a';ctx.strokeStyle=INK;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-3,-13);ctx.lineTo(6,-2);ctx.lineTo(0,0);ctx.lineTo(4,13);ctx.lineTo(-6,1);ctx.lineTo(0,-1);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
 ctx.strokeStyle=INK;ctx.lineWidth=8;for(const [px,py,r] of puffs){ctx.beginPath();ctx.arc(px,py,r,0,TAU);ctx.stroke()}
 for(const [px,py,r] of puffs){const g=ctx.createRadialGradient(px-r*.4,py-r*.5,r*.1,px,py,r);g.addColorStop(0,'#b4bfe0');g.addColorStop(1,'#46517c');ctx.fillStyle=g;ctx.beginPath();ctx.arc(px,py,r,0,TAU);ctx.fill()}
 ctx.fillStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.ellipse(-22,-50,26,9,-.2,0,TAU);ctx.fill();crownShape(-70,26,28);
 bossEye(-24,-6,14,o,'#ffe14a');bossEye(24,-6,14,o,'#ffe14a');bossBrow(-24,-27,16,1,o);bossBrow(24,-27,16,-1,o);grimace(0,27,22,22,o)}
function artTiki(o){ctx.rotate(Math.sin(o.t*1.2)*.04);
 for(let i=0;i<7;i++){ctx.save();ctx.rotate((i-3)*.3+Math.sin(o.t*2+i)*.04);ctx.translate(0,-64);ctx.fillStyle=i%2?'#36a548':'#5fd35a';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,10);ctx.quadraticCurveTo(22,-30,0,-72);ctx.quadraticCurveTo(-22,-30,0,10);ctx.fill();ctx.stroke();ctx.restore()}
 const face=new Path2D();face.roundRect(-66,-88,132,180,42);ctx.save();ctx.translate(10,9);ctx.fillStyle='#4a2c14';ctx.fill(face);ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.stroke(face);ctx.restore();
 const g=ctx.createLinearGradient(-66,0,66,0);g.addColorStop(0,'#e6a866');g.addColorStop(.6,'#b0703a');g.addColorStop(1,'#7a4a20');ctx.fillStyle=g;ctx.fill(face);
 ctx.save();ctx.clip(face);ctx.strokeStyle='rgba(60,30,10,.35)';ctx.lineWidth=2;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(-70,-70+i*30);ctx.bezierCurveTo(-20,-80+i*30,20,-60+i*30,70,-72+i*30);ctx.stroke()}ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.moveTo(-70,62);for(let i=0;i<=8;i++)ctx.lineTo(-66+i*16.5,i%2?74:62);ctx.lineTo(70,96);ctx.lineTo(-70,96);ctx.closePath();ctx.fill();ctx.restore();ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.stroke(face);
 ctx.fillStyle='#8a5326';ctx.beginPath();ctx.roundRect(-56,-54,112,16,8);ctx.fill();ctx.stroke();
 for(const s of [-1,1]){ctx.fillStyle='#2a1608';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(s*28,-20,20,15,0,0,TAU);ctx.fill();ctx.stroke();if(o.tired){ctx.strokeStyle='#ffd23f';ctx.lineWidth=2.2;ctx.beginPath();for(let a=0;a<TAU*2;a+=.3)ctx.lineTo(s*28+Math.cos(a+o.t*6)*a*1.1,-20+Math.sin(a+o.t*6)*a*.9);ctx.stroke()}else{glow(s*28,-20,28,'#ff8a2a',.75);ctx.fillStyle='#ffe680';ctx.beginPath();ctx.arc(s*28+o.lookX*6,-20+o.lookY*4,7,0,TAU);ctx.fill()}}
 ctx.fillStyle='#c98a4a';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-8,-38);ctx.lineTo(8,-38);ctx.lineTo(16,12);ctx.lineTo(-16,12);ctx.closePath();ctx.fill();ctx.stroke();
 if(o.attack>.2)glow(0,40,36,'#ff6a2a',o.attack*.7);grimace(0,40,40,26,o,'#3a0a0a');
 for(const s of [-1,1]){ctx.fillStyle='#ffd23f';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.arc(s*74,0,12,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#ff4d5e';ctx.beginPath();ctx.arc(s*74,0,5,0,TAU);ctx.fill()}}
function artBat(o){const f=Math.sin(o.t*7)*.5+.5;
 for(const s of [-1,1]){ctx.save();ctx.scale(s,1);ctx.rotate(-.12-f*.35);const wing=new Path2D();wing.moveTo(18,-10);wing.quadraticCurveTo(70,-72,132,-42);wing.lineTo(118,-6);wing.quadraticCurveTo(104,4,96,22);wing.quadraticCurveTo(84,8,68,30);wing.quadraticCurveTo(52,12,34,30);wing.closePath();
  const g=ctx.createLinearGradient(0,-60,0,30);g.addColorStop(0,'#9478d0');g.addColorStop(1,'#3d2766');ctx.fillStyle=g;ctx.fill(wing);ctx.strokeStyle=INK;ctx.lineWidth=3.5;ctx.stroke(wing);ctx.strokeStyle='rgba(27,18,64,.6)';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(22,-8);ctx.lineTo(128,-40);ctx.moveTo(30,-6);ctx.lineTo(96,20);ctx.moveTo(26,-4);ctx.lineTo(66,28);ctx.stroke();ctx.restore()}
 const gb=ctx.createRadialGradient(-10,-6,4,0,14,50);gb.addColorStop(0,'#a58ae0');gb.addColorStop(1,'#4a3080');ctx.fillStyle=gb;ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,20,34,40,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#c9b6f0';ctx.beginPath();ctx.ellipse(0,28,18,24,0,0,TAU);ctx.fill();
 for(const s of [-1,1]){ctx.fillStyle='#5d4280';ctx.strokeStyle=INK;ctx.lineWidth=3.5;ctx.beginPath();ctx.moveTo(s*12,-40);ctx.lineTo(s*30,-84);ctx.lineTo(s*36,-36);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ff9ad5';ctx.beginPath();ctx.moveTo(s*19,-44);ctx.lineTo(s*29,-72);ctx.lineTo(s*31,-42);ctx.closePath();ctx.fill()}
 const gh=ctx.createRadialGradient(-12,-38,4,0,-24,40);gh.addColorStop(0,'#b89ee8');gh.addColorStop(1,'#5a3d90');ctx.fillStyle=gh;ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-24,32,0,TAU);ctx.fill();ctx.stroke();crownShape(-52,18,20);
 bossEye(-13,-28,10,o,'#ff3b4f');bossEye(13,-28,10,o,'#ff3b4f');bossBrow(-13,-43,10,1,o);bossBrow(13,-43,10,-1,o);
 const m=o.tired?3:6+o.attack*10;ctx.fillStyle='#4a0a2a';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-6,12,m,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(s*8,-6-m*.6);ctx.lineTo(s*5,-6-m*.6+9);ctx.lineTo(s*2,-6-m*.6);ctx.fill()}
 glow(0,8,20,'#5ff0ff',.6);ctx.fillStyle='#5ff0ff';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(7,8);ctx.lineTo(0,18);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.stroke()}
function artMecha(o){const pinch=Math.sin(o.t*3)*.3;ctx.lineJoin='round';
 for(const s of [-1,1]){ctx.save();ctx.scale(s,1);ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.fillStyle='#9aa6bd';ctx.translate(66,-12);ctx.rotate(.5+Math.sin(o.t*1.5+s)*.15);rr(-8,0,16,50,6);ctx.translate(0,50);ctx.rotate(-.9);rr(-7,0,14,44,6);ctx.translate(0,44);ctx.fillStyle='#ffc21a';for(const c of [-1,1]){ctx.save();ctx.rotate(c*(.35+pinch));ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(c*14,16);ctx.lineTo(c*6,30);ctx.lineTo(c*2,14);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}ctx.restore()}
 for(const s of [-1,1]){ctx.fillStyle='#5f6b85';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(s*40-10,48,20,26,5);ctx.fill();ctx.stroke();if(o.attack>.2)glow(s*40,80,24,'#ff6a2a',o.attack)}
 ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.fillStyle='#6b7690';ctx.beginPath();ctx.moveTo(62,-46);ctx.lineTo(78,-60);ctx.lineTo(78,38);ctx.lineTo(62,54);ctx.closePath();ctx.fill();ctx.stroke();
 ctx.fillStyle='#dfe5f0';ctx.beginPath();ctx.moveTo(-62,-46);ctx.lineTo(-46,-60);ctx.lineTo(78,-60);ctx.lineTo(62,-46);ctx.closePath();ctx.fill();ctx.stroke();
 const g=ctx.createLinearGradient(0,-46,0,54);g.addColorStop(0,'#c9d3e6');g.addColorStop(1,'#7f8aa3');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(-62,-46,124,100,10);ctx.fill();hazardBand(-62,62,38,10);ctx.beginPath();ctx.roundRect(-62,-46,124,100,10);ctx.stroke();
 ctx.fillStyle=INK;ctx.beginPath();ctx.roundRect(-46,-32,92,30,12);ctx.fill();
 if(o.tired){ctx.strokeStyle='#ff5a6a';ctx.lineWidth=3.5;for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(s*18-7,-24);ctx.lineTo(s*18+7,-10);ctx.moveTo(s*18+7,-24);ctx.lineTo(s*18-7,-10);ctx.stroke()}}else{const ex=o.lookX*26;glow(ex,-17,32,'#ff3c50',.8);ctx.fillStyle='#ff3b4f';ctx.beginPath();ctx.ellipse(ex,-17,14,8,0,0,TAU);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ex-4,-19,3,0,TAU);ctx.fill()}
 ctx.fillStyle='#5f6b85';ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-26,6,52,24,5);ctx.fill();ctx.stroke();ctx.lineWidth=2;for(let i=-18;i<=18;i+=9){ctx.beginPath();ctx.moveTo(i,9);ctx.lineTo(i,27);ctx.stroke()}
 ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,-60);ctx.lineTo(10,-84);ctx.stroke();ctx.fillStyle=Math.sin(o.t*8)>0?'#ff3b4f':'#ffd23f';ctx.beginPath();ctx.arc(10,-88,6,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#eef3fb';for(const [px,py] of [[-54,-38],[54,-38],[-54,30],[54,30]]){ctx.beginPath();ctx.arc(px,py,3,0,TAU);ctx.fill()}}
function artUFO(o){ctx.rotate(Math.sin(o.t*1.3)*.07);ctx.lineJoin='round';
 ctx.fillStyle='rgba(160,240,255,.5)';ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-12,52,58,0,Math.PI,TAU);ctx.closePath();ctx.fill();
 ctx.lineWidth=3;ctx.strokeStyle=INK;for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(s*8,-56);ctx.lineTo(s*16,-70);ctx.stroke();ctx.fillStyle='#ff7ad9';ctx.beginPath();ctx.arc(s*16,-72,4,0,TAU);ctx.fill();ctx.stroke()}
 const ag=ctx.createRadialGradient(-8,-44,3,0,-34,30);ag.addColorStop(0,'#c4ffb0');ag.addColorStop(1,'#46c25a');ctx.fillStyle=ag;ctx.beginPath();ctx.ellipse(0,-34,24,27,0,0,TAU);ctx.fill();ctx.stroke();
 for(const s of [-1,1]){ctx.save();ctx.translate(s*10,-38);ctx.rotate(s*.45);ctx.fillStyle=INK;ctx.beginPath();ctx.ellipse(0,0,6,10,0,0,TAU);ctx.fill();ctx.restore();if(o.tired){ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();for(let a=0;a<TAU*2;a+=.4)ctx.lineTo(s*10+Math.cos(a+o.t*6)*a*.6,-38+Math.sin(a+o.t*6)*a*.6);ctx.stroke()}else{ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s*10+o.lookX*2-1.5,-41+o.lookY*2,2.2,0,TAU);ctx.fill()}}
 ctx.strokeStyle=INK;ctx.lineWidth=2.5;ctx.beginPath();if(o.tired)ctx.arc(0,-18,4,Math.PI*1.1,Math.PI*1.9);else ctx.arc(0,-24,6,.2*Math.PI,.8*Math.PI,true);ctx.stroke();
 ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-12,52,58,0,Math.PI,TAU);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,-12,42,48,0,Math.PI*1.15,Math.PI*1.4);ctx.stroke();
 const sg=ctx.createLinearGradient(0,-24,0,26);sg.addColorStop(0,'#f4f7fc');sg.addColorStop(.5,'#b8c2d6');sg.addColorStop(1,'#6b7690');ctx.fillStyle=sg;ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,0,124,30,0,0,TAU);ctx.fill();ctx.stroke();
 ctx.fillStyle='#5f6b85';ctx.beginPath();ctx.ellipse(0,14,70,16,0,0,Math.PI);ctx.fill();ctx.stroke();
 for(let k=0;k<9;k++){ctx.fillStyle=['#ff4d5e','#ffd23f','#44d9ff','#4fd36b','#a273ff'][(k+Math.floor(o.t*8))%5];ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(-96+k*24,4,5,0,TAU);ctx.fill();ctx.stroke()}
 for(const s of [-1,0,1]){ctx.fillStyle='#3a4256';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(s*36-6,24,12,16,3);ctx.fill();ctx.stroke();if(o.attack>.2)glow(s*36,44,20,'#7cf08a',o.attack)}}
const COSMIC_SPOTS=spotsFor(21,7,['#ff7ad9','#5ff0ff','#2a0f56'],.08,.18);
function artCosmic(o){ctx.lineCap='round';
 for(let i=0;i<5;i++){const bx=(i-2)*28,path=()=>{ctx.beginPath();ctx.moveTo(bx,30);ctx.bezierCurveTo(bx+Math.sin(o.t*2+i)*30,70,bx-Math.sin(o.t*2.4+i)*30,100,bx+Math.sin(o.t*3+i)*22,130)};path();ctx.strokeStyle=INK;ctx.lineWidth=15;ctx.stroke();path();ctx.strokeStyle=i%2?'#7a3cff':'#c03cff';ctx.lineWidth=9;ctx.stroke()}
 planetRing(0,0,62,'#5ff0ff',true);sphere(0,0,62,{base:['#dcc2ff','#7a3cff','#2a0f56'],spots:COSMIC_SPOTS,rot:o.t*.4,glow:'#a273ff'});
 const blink=Math.max(0,Math.sin(o.t*.9))**40,eh=(o.tired?9:28)*(1-blink)+1;ctx.save();ctx.beginPath();ctx.ellipse(0,-4,40,eh,0,0,TAU);ctx.clip();ctx.fillStyle='#fff';ctx.fillRect(-42,-34,84,60);
 const ix=o.lookX*12,iy=-4+o.lookY*6,ig=ctx.createRadialGradient(ix,iy,2,ix,iy,20);ig.addColorStop(0,'#5ff0ff');ig.addColorStop(1,'#7a3cff');ctx.fillStyle=ig;ctx.beginPath();ctx.arc(ix,iy,20,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.5)';ctx.lineWidth=2;for(let k=0;k<6;k++){const a=k*TAU/6+o.t;ctx.beginPath();ctx.moveTo(ix+Math.cos(a)*6,iy+Math.sin(a)*6);ctx.lineTo(ix+Math.cos(a+.6)*17,iy+Math.sin(a+.6)*17);ctx.stroke()}
 ctx.fillStyle=INK;if(o.tired){ctx.strokeStyle=INK;ctx.lineWidth=2;ctx.beginPath();for(let a=0;a<TAU*2;a+=.3)ctx.lineTo(ix+Math.cos(a+o.t*6)*a*1.1,iy+Math.sin(a+o.t*6)*a*1.1);ctx.stroke()}else{ctx.beginPath();ctx.ellipse(ix,iy,4.5,15,0,0,TAU);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ix-7,iy-7,4,0,TAU);ctx.fill()}ctx.restore();
 ctx.strokeStyle=INK;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-4,40,eh,0,0,TAU);ctx.stroke();planetRing(0,0,62,'#5ff0ff',false);
 ctx.fillStyle='#fff6b0';for(let k=0;k<5;k++){const a=o.t*1.2+k*TAU/5;star(Math.cos(a)*100,Math.sin(a)*30,6,2.4,4);ctx.fill()}}
const BOSSES={
 sky:{name:'THUNDER KING',title:'STORM BOSS',art:artStorm,attacks:['lightning','hail','gust']},
 jungle:{name:'TIKI TITAN',title:'JUNGLE BOSS',art:artTiki,attacks:['darts','coconuts','firering']},
 cave:{name:'BAT QUEEN',title:'CAVE BOSS',art:artBat,attacks:['sonic','stalactites','swarm']},
 factory:{name:'MECHA CRUSHER',title:'FACTORY BOSS',art:artMecha,attacks:['laser','missiles','saws']},
 space:{name:'UFO OVERLORD',title:'SPACE BOSS',art:artUFO,attacks:['plasma','tractor','burst']},
 universe:{name:'STAR DEVOURER',title:'COSMIC BOSS',art:artCosmic,attacks:['spiral','blackhole','ring']}};

// ---------- Attacks ----------
function bossShot(b,o){b.shots.push({age:0,kind:'orb',...o})}
function later(b,delay,fn){b.timers.push({at:b.clock+delay,fn})}
const mouth=b=>({x:b.x,y:b.y+44*b.scale});
function aimed(b,speed,o={}){const m=mouth(b),a=Math.atan2(balloonY()-m.y,x*W-m.x)+(o.spread||0),v=speed*b.sp;bossShot(b,{x:m.x,y:m.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:8,life:6,...o})}
function fan(b,n,a0,a1,speed,o){const m=mouth(b),v=speed*b.sp;for(let i=0;i<n;i++){const a=a0+(a1-a0)*i/(n-1);bossShot(b,{x:m.x,y:m.y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:8,life:6,...o})}}
// Pick drop lanes across the width but always leave at least three lanes free.
function lanes(n){const all=[0,1,2,3,4,5,6].sort(()=>Math.random()-.5).slice(0,Math.min(n,4));return all.map(k=>(k+.5)/7*W)}
const ringShot=(b,style)=>bossShot(b,{kind:'ring',style,cx:b.x,cy:b.y+16*b.scale,speed:135*b.sp,thick:14,gap:Math.PI/2+rand(-.8,.8),gapW:.85,max:Math.hypot(W,H)});
const ATTACKS={
 lightning(b){for(let i=0;i<2;i++)later(b,i*.7,()=>{bossShot(b,{kind:'strike',style:'bolt',x:i<1?x*W:rand(.15,.85)*W,w:40,warn:1,dur:.28});gameSound.effect('zap')});return 15},
 hail(b){for(let w=0;w<2;w++)later(b,w*.8,()=>fan(b,4,Math.PI*.3+(w?.1:0),Math.PI*.7+(w?.1:0),140,{style:'hail',r:8}));gameSound.effect('pew');return 15},
 gust(b){b.wind={dir:x>.5?1:-1,time:2.2};popup(W/2,H*.45,'GUST!','#bff4ff',34);for(let i=0;i<2;i++)later(b,.6+i*.8,()=>aimed(b,155,{style:'hail',r:8}));return 14},
 darts(b){for(let i=0;i<3;i++)later(b,i*.32,()=>{aimed(b,210,{style:'dart',r:6});gameSound.effect('pew')});return 15},
 coconuts(b){lanes(4).forEach((fx,i)=>later(b,i*.15,()=>bossShot(b,{kind:'faller',style:'coconut',x:fx,y:-30,vy:240*b.sp,r:12,warn:1})));return 15},
 firering(b){ringShot(b,'fire');gameSound.effect('roar');return 15},
 sonic(b){ringShot(b,'sonic');later(b,1.2,()=>ringShot(b,'sonic'));gameSound.effect('zap');return 15},
 stalactites(b){lanes(4).forEach((fx,i)=>later(b,i*.12,()=>bossShot(b,{kind:'faller',style:'spike',x:fx,y:-30,vy:270*b.sp,r:11,warn:1})));return 15},
 swarm(b){for(let i=0;i<3;i++)later(b,i*.35,()=>aimed(b,135,{style:'bat',r:10,home:.9,turn:2}));return 15},
 laser(b){for(const s of [-1,1])later(b,s>0?.7:0,()=>{const ox=b.x+s*40*b.scale,oy=b.y+80*b.scale;bossShot(b,{kind:'beam',style:'laser',x:ox,y:oy,ang:Math.atan2(balloonY()-oy,x*W-ox),len:Math.hypot(W,H)*1.3,w:12,warn:1,dur:.3})});gameSound.effect('zap');return 15},
 missiles(b){for(let i=0;i<2;i++)later(b,i*.45,()=>{aimed(b,120,{style:'missile',r:8,home:1.1,turn:.9,life:4,spread:(i?.5:-.5)});gameSound.effect('pew')});return 15},
 saws(b){for(const s of [-1,1])bossShot(b,{style:'saw',x:b.x+s*50*b.scale,y:b.y+40*b.scale,vx:s*125*b.sp,vy:115*b.sp,r:14,bounce:true,life:3.2});return 15},
 plasma(b){for(let w=0;w<2;w++)later(b,w*.9,()=>{fan(b,5,Math.PI*.25+(w?.1:0),Math.PI*.75+(w?.1:0),135,{style:'plasma',r:8});gameSound.effect('pew')});return 15},
 tractor(b){const fromLeft=x>.5;bossShot(b,{kind:'sweep',style:'tractor',x0:fromLeft?W*.06:W*.94,x1:fromLeft?W*.5:W*.5,w:64,warn:1.1,dur:2.6});return 15},
 burst(b){for(let i=0;i<2;i++)later(b,i*.7,()=>{for(const d of [-.22,0,.22])aimed(b,165,{style:'plasma',r:7,spread:d});gameSound.effect('pew')});return 14},
 spiral(b){for(let i=0;i<8;i++)later(b,i*.2,()=>{const a=Math.PI*(.2+.6*(.5+.5*Math.sin(i*.7)));fan(b,2,a,Math.PI-a,120,{style:'star',r:7})});return 15},
 blackhole(b){bossShot(b,{kind:'hole',style:'hole',x:rand(.25,.75)*W,y:H*.42,r:22,warn:.9,dur:2.8,pull:.5});for(let i=0;i<3;i++)later(b,1+i*.7,()=>bossShot(b,{kind:'faller',style:'meteor',x:lanes(1)[0],y:-30,vy:230*b.sp,r:11,warn:.9}));gameSound.effect('zap');return 16},
 ring(b){ringShot(b,'cosmic');later(b,1.2,()=>ringShot(b,'cosmic'));return 15}};

// ---------- Fight flow ----------
function startBoss(){const def=BOSSES[stage.id]||BOSSES.sky,level=save.bossWins&&save.bossWins[stage.id]?Math.min(3,save.bossWins[stage.id]):0;
 boss={def,phase:'clear',age:0,animT:0,clock:0,x:W/2,y:-220,scale:Math.min(1,W/430),stamina:100,shots:[],timers:[],cool:1.2,last:-1,attack:0,level,sp:.85+.07*level,pace:1,wind:null,fatal:null,hidden:false,freeze:false};
 for(const o of obstacles)if(o.leaving===undefined)o.leaving=0;for(const h of critters){if(h.dormant)h.gone=true;else knock(h,critterPos(h))}critters=critters.filter(h=>!h.gone);
 closeCoinRow();announce('WARNING!','BOSS INCOMING','power','skull');gameSound.effect('siren');shake=Math.max(shake,6)}
function setPhase(p){boss.phase=p;boss.age=0}
function showVersus(){const v=$('#versus');$('#vs-boss-name').textContent=boss.def.name;$('#vs-boss-title').textContent=boss.def.title;$('#vs-hero-name').textContent=(SKINS[save.skin]||SKINS.classic).name.toUpperCase();v.hidden=false;v.classList.remove('play');void v.offsetWidth;v.classList.add('play');gameSound.effect('vs');setTimeout(()=>gameSound.effect('roar'),700)}
function renderVersus(){const main=ctx,s=performance.now()/1000;
 const hc=$('#vs-hero').getContext('2d');hc.setTransform(1,0,0,1,0,0);hc.clearRect(0,0,240,240);hc.setTransform(2.8,0,0,2.8,120,128);ctx=hc;ctx.rotate(Math.sin(s*3)*.08);drawBalloonBody(SKINS[save.skin]||SKINS.classic,s,'cool',0);
 const bc=$('#vs-boss').getContext('2d');bc.setTransform(1,0,0,1,0,0);bc.clearRect(0,0,320,260);bc.setTransform(1.05,0,0,1.05,160,138+Math.sin(s*2)*4);ctx=bc;boss.def.art({t:s,tired:false,attack:.5+.5*Math.sin(s*4),lookX:-.7,lookY:.6});ctx=main}
function bossPace(){return boss?boss.pace:1}
function updateBoss(dt,real){caveWallScale+=((boss&&boss.phase!=='done'?.15:1)-caveWallScale)*Math.min(1,real*1.5);if(!boss||state==='dead')return;const b=boss;b.animT+=real;b.attack=Math.max(0,b.attack-real*1.4);if(b.wind&&(b.wind.time-=dt)<=0)b.wind=null;
 const target=b.phase==='clear'||b.phase==='done'?1:.35;b.pace+=(target-b.pace)*Math.min(1,real*2);
 for(const o of obstacles)if(o.leaving!==undefined)o.leaving+=real;obstacles=obstacles.filter(o=>o.leaving===undefined||o.leaving<.6);
 b.freeze=b.phase==='versus'||b.phase==='fatality';
 if(b.phase==='clear'){if((b.age+=real)>1.1){setPhase('versus');showVersus()}return}
 if(b.phase==='versus'){if((b.age+=real)>2.6){$('#versus').hidden=true;setPhase('enter')}return}
 const homeX=W/2+Math.sin(b.clock*.55)*W*.24,homeY=Math.max(H*.27,200*b.scale+40)+Math.sin(b.clock*1.4)*10;
 if(b.phase==='enter'){b.age+=dt;b.clock+=dt;const k=Math.min(1,b.age/1.1);b.x=homeX;b.y=-220+(homeY+220)*easeOut(k);if(k>=1){setPhase('fight');announce('FIGHT!','','go');gameSound.effect('roar');shake=Math.max(shake,14)}return}
 if(b.phase==='fight'){b.clock+=dt;b.x+=(homeX-b.x)*Math.min(1,dt*3);b.y+=(homeY-b.y)*Math.min(1,dt*3);
  for(const tm of b.timers)if(b.clock>=tm.at){tm.done=true;tm.fn()}b.timers=b.timers.filter(tm=>!tm.done);
  b.stamina-=dt*2.2;if((b.cool-=dt)<=0&&b.stamina>0){let k;do k=Math.floor(Math.random()*b.def.attacks.length);while(k===b.last&&b.def.attacks.length>1);b.last=k;b.stamina-=ATTACKS[b.def.attacks[k]](b);b.attack=1;b.cool=rand(3,3.6)/b.sp}
  if(b.stamina<=0&&!b.timers.length){b.stamina=0;setPhase('tired');for(const s of b.shots)burst(s.x||s.cx||x*W,s.y||s.cy||0,4,{type:'puff',colors:['#ffffff'],speed:[20,60],size:[5,9],life:[.3,.5]});b.shots=[];b.wind=null;announce('TIRED!','TAP FATALITY!','fatal','skull');gameSound.effect('charged')}}
 if(b.phase==='tired'){b.clock+=dt*.3;b.x+=(W/2-b.x)*Math.min(1,dt*2);b.y+=(Math.max(H*.31,200*b.scale+70)+Math.sin(b.animT*2)*6-b.y)*Math.min(1,dt*2)}
 if(b.phase==='fatality'){b.age+=real;const f=b.fatal;f.p=Math.min(1,b.age/FATALITY_TIME);f.pose={};f.balloon=null;f.def.pose(f.p,b,f);if(f.p>=1)bossDefeated()}
 if(b.phase==='done'&&(b.age+=real)>3.2){endBoss();return}
 updateShots(b,dt)}
function updateShots(b,dt){const bx=x*W,by=balloonY()-5,br=14;
 for(const s of b.shots){s.age+=dt;
  if(s.kind==='orb'){if(s.home&&s.age<s.home){const want=Math.atan2(by-s.y,bx-s.x),cur=Math.atan2(s.vy,s.vx),sp=Math.hypot(s.vx,s.vy);let d=want-cur;while(d>Math.PI)d-=TAU;while(d<-Math.PI)d+=TAU;const na=cur+clamp(d,-s.turn*dt,s.turn*dt);s.vx=Math.cos(na)*sp;s.vy=Math.sin(na)*sp}
   s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.bounce){if(s.x<s.r||s.x>W-s.r){s.vx*=-1;s.x=clamp(s.x,s.r,W-s.r)}if(s.y<H*.1||s.y>H-30){s.vy*=-1;s.y=clamp(s.y,H*.1,H-30)}}
   if(s.age>s.life||s.y>H+50||s.y<-80||s.x<-60||s.x>W+60)s.dead=true;else if(Math.hypot(s.x-bx,s.y-by)<s.r+br)bossHit(s)}
  else if(s.kind==='faller'){if(s.age>s.warn){s.y+=s.vy*dt;if(s.y>H+50)s.dead=true;else if(Math.hypot(s.x-bx,s.y-by)<s.r+br)bossHit(s)}}
  else if(s.kind==='strike'){if(s.age>s.warn+s.dur)s.dead=true;else if(s.age>s.warn&&!s.hit&&Math.abs(bx-s.x)<s.w/2+br*.8)bossHit(s)}
  else if(s.kind==='beam'){if(s.age>s.warn+s.dur)s.dead=true;else if(s.age>s.warn&&!s.hit){const dx=Math.cos(s.ang),dy=Math.sin(s.ang),px=bx-s.x,py=by-s.y,along=px*dx+py*dy;if(along>0&&Math.abs(px*dy-py*dx)<s.w/2+br*.8)bossHit(s)}}
  else if(s.kind==='ring'){const r=s.age*s.speed;if(r>s.max)s.dead=true;else if(!s.hit){const d=Math.hypot(bx-s.cx,by-s.cy);if(Math.abs(d-r)<s.thick/2+br*.6){let a=Math.atan2(by-s.cy,bx-s.cx)-s.gap;while(a>Math.PI)a-=TAU;while(a<-Math.PI)a+=TAU;if(Math.abs(a)>s.gapW)bossHit(s)}}}
  else if(s.kind==='sweep'){if(s.age>s.warn+s.dur+.2)s.dead=true;else{s.x=s.x0+(s.x1-s.x0)*clamp((s.age-s.warn)/s.dur,0,1);if(s.age>s.warn&&!s.hit&&Math.abs(bx-s.x)<s.w/2+br*.8)bossHit(s)}}
  else if(s.kind==='hole'){if(s.age>s.warn+s.dur)s.dead=true;else if(s.age>s.warn){vx+=Math.sign(s.x-bx)*s.pull*dt*Math.min(1,160/Math.max(40,Math.abs(s.x-bx)));if(!s.hit&&Math.hypot(s.x-bx,s.y-by)<s.r+br*.6)bossHit(s)}}
  if(state!=='flying')return}
 b.shots=b.shots.filter(s=>!s.dead)}
// A boss shot reached the balloon: boosts shrug it off, a shield absorbs it, otherwise the balloon pops.
function bossHit(s){if(smashing()){if(s.kind==='orb'||s.kind==='faller'){s.dead=true;burst(s.x,s.y,8,{colors:['#fff','#ffd23f'],speed:[80,220],life:[.2,.4]})}else s.hit=true;return}
 if(shield>0){breakShield();if(s.kind==='orb'||s.kind==='faller')s.dead=true;else s.hit=true;return}finish()}
function startFatality(){if(!boss||boss.phase!=='tired'||state!=='flying')return;const def=FATALITIES[save.skin]||FATALITIES.classic;setPhase('fatality');boss.fatal={def,p:0,pose:{},balloon:null,fired:new Set(),at(th,fn){if(this.p>=th&&!this.fired.has(th)){this.fired.add(th);fn()}}};announce(def.name,'FATALITY!','fatal','skull');gameSound.effect('fatality');shake=Math.max(shake,8)}
function bossDefeated(){const b=boss,reward=500+100*b.level+(save.skin==='gold'?100:0);spawnRewardCoins(b,reward);
 save.bossWins=save.bossWins||{};save.bossWins[stage.id]=(save.bossWins[stage.id]||0)+1;persist();
 announce('BOSS DEFEATED!',`+${reward} COINS`,'record','trophy');confetti(50);gameSound.effect('record');b.hidden=true;b.shots=[];setPhase('done')}
function endBoss(){boss=null;nextBossTime=flightTime+BOSS_INTERVAL;nextObstacle=alt+H/worldScale*.95;prevLedge={a:nextObstacle-300,c:.5};coinCursor=Math.max(coinCursor,nextObstacle-260)}
// Boss reward: coins burst out across the screen, hang for a moment, then all fly into the balloon.
function spawnRewardCoins(b,n){const cx=b.x,cy=Math.max(60,b.y);for(let i=0;i<n;i++){const a=rand(0,TAU),sp=rand(60,560);rewardCoins.push({x:cx,y:cy,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-40,age:0,hold:rand(.7,1.3),phase:rand(0,TAU)})}}
function updateRewardCoins(real){if(!rewardCoins.length)return;const bx=x*W,by=balloonY()-5;let got=0;
 for(const c of rewardCoins){c.age+=real;if(c.age<c.hold){const d=Math.exp(-2.6*real);c.vx*=d;c.vy*=d;c.vy+=30*real;c.x=clamp(c.x+c.vx*real,8,W-8);c.y=clamp(c.y+c.vy*real,30,H-30)}
  else{const dx=bx-c.x,dy=by-c.y,dist=Math.hypot(dx,dy)||1,step=Math.min(dist,(260+(c.age-c.hold)*1500)*real);c.x+=dx/dist*step;c.y+=dy/dist*step;if(dist<18){c.done=true;got++}}}
 if(!got)return;rewardCoins=rewardCoins.filter(c=>!c.done);coinCount+=got;shownCoins+=got;squashV+=Math.min(4,got*.3);if(performance.now()-rewardSound>55){rewardSound=performance.now();gameSound.effect('coin',1+Math.floor(Math.random()*12))}if(Math.random()<.3)burst(bx,by,3,{type:'star',colors:['#ffd23f','#fff'],speed:[60,160],size:[3,5],life:[.3,.5]});bump($('#coin-pill'));if(!rewardCoins.length){popup(bx,by-80,'JACKPOT!','#ffd23f',40);gameSound.effect('record')}}
function drawRewardCoins(){if(!rewardCoins.length)return;ctx.save();ctx.beginPath();for(const c of rewardCoins){const w=Math.max(.25,Math.abs(Math.cos(c.age*8+c.phase)))*7;ctx.moveTo(c.x+w,c.y);ctx.ellipse(c.x,c.y,w,7,0,0,TAU)}ctx.fillStyle='#ffcf2e';ctx.fill();ctx.strokeStyle=INK;ctx.lineWidth=1.6;ctx.stroke();ctx.beginPath();for(const c of rewardCoins){ctx.moveTo(c.x-1,c.y-2);ctx.arc(c.x-2,c.y-2,1.8,0,TAU)}ctx.fillStyle='#fff6c2';ctx.fill();ctx.restore()}

// ---------- Drawing ----------
function drawBossBody(b){const F=(b.fatal&&b.fatal.pose)||{};if(b.hidden||F.alpha===0)return;const o={t:b.animT,tired:b.phase==='tired'||b.phase==='fatality',attack:b.attack,lookX:clamp((x*W-b.x)/150,-1,1),lookY:clamp((balloonY()-b.y)/250,-1,1)},sc=b.scale*(F.scale===undefined?1:F.scale);
 ctx.save();ctx.translate(b.x+(F.dx||0),b.y+(F.dy||0));ctx.rotate(F.rot||0);ctx.scale(sc*(F.sx||1),sc*(F.sy||1));if(F.alpha!==undefined)ctx.globalAlpha=F.alpha;
 if(F.gold||F.split){if(!bossBuf)bossBuf=document.createElement('canvas');bossBuf.width=720;bossBuf.height=720;const c=bossBuf.getContext('2d'),main=ctx;c.setTransform(2,0,0,2,360,360);ctx=c;b.def.art(o);if(F.gold){ctx.globalCompositeOperation='source-atop';ctx.fillStyle=`rgba(255,196,40,${F.gold*.85})`;ctx.fillRect(-180,-180,360,360);ctx.fillStyle=`rgba(255,255,255,${F.gold*.25})`;ctx.fillRect(-180,-180,360,120);ctx.globalCompositeOperation='source-over'}ctx=main;
  if(F.split){const k=F.split;ctx.globalAlpha*=1-k*.5;for(const s of [-1,1]){ctx.save();ctx.translate(s*k*60,k*k*160);ctx.rotate(s*k*.5);ctx.beginPath();ctx.rect(s<0?-180:0,-180,180,360);ctx.clip();ctx.drawImage(bossBuf,-180,-180,360,360);ctx.restore()}}else ctx.drawImage(bossBuf,-180,-180,360,360)}
 else b.def.art(o);
 if(F.hurt){ctx.globalAlpha=F.hurt*.4;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,90,0,TAU);ctx.fill()}ctx.restore();
 if(b.phase==='tired'){ctx.save();for(let k=0;k<4;k++){const a=b.animT*3+k*TAU/4;ctx.fillStyle=k%2?'#ffd23f':'#fff';ctx.strokeStyle=INK;ctx.lineWidth=1.5;star(b.x+Math.cos(a)*60*b.scale,b.y-96*b.scale+Math.sin(a)*14,8,3.4,5);ctx.fill();ctx.stroke()}ctx.fillStyle='#8fd8ff';for(const s of [-1,1]){const q=(b.animT*.8+(s>0?.5:0))%1;ctx.globalAlpha=1-q;ctx.beginPath();ctx.ellipse(b.x+s*80*b.scale,b.y-40*b.scale+q*40,4,7,0,0,TAU);ctx.fill()}ctx.restore()}}
function drawShot(s){ctx.save();ctx.lineJoin='round';ctx.lineCap='round';
 if(s.kind==='strike'){if(s.age<s.warn){const a=.35+.35*Math.sin(s.age*30);ctx.fillStyle=`rgba(255,220,60,${a*.35})`;ctx.fillRect(s.x-s.w/2,0,s.w,H);ctx.setLineDash([10,8]);ctx.strokeStyle=`rgba(255,80,80,${a+.3})`;ctx.lineWidth=3;ctx.strokeRect(s.x-s.w/2,0,s.w,H)}else{const top=boss?boss.y+30:0;ctx.beginPath();ctx.moveTo(s.x,top);for(let y=top;y<H;y+=28)ctx.lineTo(s.x+(Math.random()-.5)*s.w,y);ctx.lineTo(s.x,H);ctx.strokeStyle='rgba(255,230,90,.45)';ctx.lineWidth=s.w;ctx.stroke();ctx.strokeStyle=INK;ctx.lineWidth=13;ctx.stroke();ctx.strokeStyle='#ffe14a';ctx.lineWidth=9;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}}
 else if(s.kind==='beam'){ctx.translate(s.x,s.y);ctx.rotate(s.ang);if(s.age<s.warn){ctx.setLineDash([12,10]);ctx.strokeStyle=`rgba(255,60,80,${.5+.4*Math.sin(s.age*30)})`;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(s.len,0);ctx.stroke();glow(0,0,18+s.age*20,'#ff3c50',.8)}else{ctx.strokeStyle='rgba(255,60,80,.4)';ctx.lineWidth=s.w*2.2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(s.len,0);ctx.stroke();ctx.strokeStyle='#ff3b4f';ctx.lineWidth=s.w;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=s.w*.35;ctx.stroke()}}
 else if(s.kind==='ring'){const r=s.age*s.speed,c={fire:['#ffb020','#ff4a2a'],sonic:['rgba(201,168,255,.9)','rgba(122,60,255,.8)'],cosmic:['#5ff0ff','#a273ff']}[s.style];ctx.beginPath();ctx.arc(s.cx,s.cy,r,s.gap+s.gapW,s.gap-s.gapW+TAU);ctx.strokeStyle=INK;ctx.lineWidth=s.thick+6;ctx.stroke();ctx.strokeStyle=c[1];ctx.lineWidth=s.thick;ctx.stroke();ctx.strokeStyle=c[0];ctx.lineWidth=s.thick*.45;ctx.stroke()}
 else if(s.kind==='sweep'){const gx=s.age<s.warn?s.x0:s.x;if(s.age<s.warn){const a=.4+.3*Math.sin(s.age*24);ctx.fillStyle=`rgba(124,240,138,${a*.3})`;const lo=Math.min(s.x0,s.x1)-s.w/2,hi=Math.max(s.x0,s.x1)+s.w/2;ctx.fillRect(lo,0,hi-lo,H);ctx.fillStyle=`rgba(255,80,80,${a+.3})`;ctx.font=`28px ${FONT}`;ctx.textAlign='center';ctx.fillText(s.x1>s.x0?'>>>':'<<<',(s.x0+s.x1)/2,H*.5)}else{const top=boss?boss.y+30:0,g=ctx.createLinearGradient(gx-s.w/2,0,gx+s.w/2,0);g.addColorStop(0,'rgba(124,240,138,0)');g.addColorStop(.5,'rgba(160,255,170,.75)');g.addColorStop(1,'rgba(124,240,138,0)');ctx.fillStyle=g;ctx.fillRect(gx-s.w/2,top,s.w,H-top);ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=3;for(let k=0;k<6;k++){const y=top+((s.age*200+k*H/6)%(H-top));ctx.beginPath();ctx.ellipse(gx,y,s.w*.4,6,0,0,TAU);ctx.stroke()}}}
 else if(s.kind==='hole'){const k=s.age<s.warn?s.age/s.warn:1;ctx.translate(s.x,s.y);for(let i=0;i<4;i++){ctx.rotate(s.age*3+i);ctx.strokeStyle=['#7a3cff','#5ff0ff','#ff7ad9','#c9a8ff'][i];ctx.lineWidth=5;ctx.globalAlpha=.75*k;ctx.beginPath();ctx.ellipse(0,0,(s.r+20+i*10)*k,(s.r*.5+i*4)*k,0,0,Math.PI*1.4);ctx.stroke()}ctx.globalAlpha=1;const g=ctx.createRadialGradient(0,0,0,0,0,s.r*1.4*k+1);g.addColorStop(0,'#000');g.addColorStop(.7,'#0a0020');g.addColorStop(1,'rgba(122,60,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,s.r*1.4*k+1,0,TAU);ctx.fill()}
 else if(s.kind==='faller'&&s.age<s.warn){const a=Math.sin(s.age*25)>-.2;ctx.fillStyle='rgba(255,80,80,.15)';ctx.fillRect(s.x-s.r-4,0,s.r*2+8,H);if(a){ctx.translate(s.x,Math.min(H*.3,215));ctx.fillStyle='#ff4d5e';ctx.strokeStyle=INK;ctx.lineWidth=3.5;ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(16,12);ctx.lineTo(-16,12);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font=`20px ${FONT}`;ctx.textAlign='center';ctx.fillText('!',0,9)}}
 else{ctx.translate(s.x,s.y);const r=s.r,ang=Math.atan2(s.vy||1,s.vx||0);ctx.strokeStyle=INK;ctx.lineWidth=2.5;
  if(s.style==='hail'){orb(0,0,r,'#ffffff','#bfe9ff','#6fb8e8');ring(0,0,r,2.5)}
  else if(s.style==='dart'){ctx.rotate(ang);ctx.fillStyle='#ff4d5e';ctx.beginPath();ctx.moveTo(-14,-5);ctx.lineTo(-6,0);ctx.lineTo(-14,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#b07a48';ctx.fillRect(-8,-2,14,4);ctx.strokeRect(-8,-2,14,4);ctx.fillStyle='#e6ecf5';ctx.beginPath();ctx.moveTo(6,-4);ctx.lineTo(14,0);ctx.lineTo(6,4);ctx.closePath();ctx.fill();ctx.stroke();glow(0,0,14,'#ff8a2a',.4)}
  else if(s.style==='coconut'){ctx.rotate(s.age*6);orb(0,0,r,'#b07a48','#7a4a20','#3d2410');ring(0,0,r,3);ctx.fillStyle='#2a1608';for(const a of [0,2.1,4.2]){ctx.beginPath();ctx.arc(Math.cos(a)*r*.4,Math.sin(a)*r*.4,2.2,0,TAU);ctx.fill()}}
  else if(s.style==='spike'){ctx.fillStyle='#8a6cc4';ctx.beginPath();ctx.moveTo(-r,-r*1.6);ctx.lineTo(r,-r*1.6);ctx.lineTo(0,r*1.4);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#5ff0ff';ctx.beginPath();ctx.moveTo(-r*.3,-r*1.2);ctx.lineTo(r*.2,-r*1.2);ctx.lineTo(0,r*.6);ctx.closePath();ctx.fill()}
  else if(s.style==='meteor'){const g=ctx.createLinearGradient(0,0,0,-r*6);g.addColorStop(0,'rgba(255,200,60,.9)');g.addColorStop(1,'rgba(255,60,40,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-r,0);ctx.quadraticCurveTo(0,-r*7,r,0);ctx.closePath();ctx.fill();orb(0,0,r,'#ffb08a','#a8402a','#4a1010');ring(0,0,r,3)}
  else if(s.style==='bat'){ctx.rotate(ang+Math.PI/2);const f=Math.sin(s.age*20);ctx.fillStyle='#4a3466';for(const sd of [-1,1]){ctx.beginPath();ctx.moveTo(sd*4,0);ctx.lineTo(sd*18,-8*f);ctx.lineTo(sd*12,6);ctx.closePath();ctx.fill();ctx.stroke()}ctx.fillStyle='#6a4c94';ctx.beginPath();ctx.arc(0,0,7,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.arc(-2.5,1,1.6,0,TAU);ctx.arc(2.5,1,1.6,0,TAU);ctx.fill()}
  else if(s.style==='missile'){ctx.rotate(ang);const fl=8+Math.random()*6;ctx.fillStyle='#ffb020';ctx.beginPath();ctx.moveTo(-12,-4);ctx.lineTo(-12-fl,0);ctx.lineTo(-12,4);ctx.closePath();ctx.fill();ctx.fillStyle='#e6ecf5';ctx.beginPath();ctx.roundRect(-12,-5,20,10,4);ctx.fill();ctx.stroke();ctx.fillStyle='#ff4d5e';ctx.beginPath();ctx.moveTo(8,-5);ctx.lineTo(15,0);ctx.lineTo(8,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-10,-5);ctx.lineTo(-14,-10);ctx.lineTo(-6,-5);ctx.moveTo(-10,5);ctx.lineTo(-14,10);ctx.lineTo(-6,5);ctx.fill();ctx.stroke()}
  else if(s.style==='saw')sawBlade(0,r,s.age*14);
  else if(s.style==='star'){ctx.rotate(s.age*8);ctx.fillStyle='#fff6b0';star(0,0,r*1.3,r*.55,4);ctx.fill();ctx.stroke();glow(0,0,r*2,'#ffe680',.5)}
  else{glow(0,0,r*2.4,'#7cf08a',.7);orb(0,0,r,'#ffffff','#9dff8a','#2fbf4f');ring(0,0,r,2.5)}}
 ctx.restore()}
function drawBossLayer(){if(!boss||boss.phase==='clear'||boss.phase==='versus')return;const f=boss.fatal;if(f&&f.def.under)f.def.under(f.p,boss,f);drawBossBody(boss);for(const s of boss.shots)drawShot(s)}
function drawBossFx(){const f=boss&&boss.fatal;if(f&&boss.phase==='fatality'&&f.def.draw)f.def.draw(f.p,boss,f)}

// ---------- Fatalities: one finishing move per balloon skin ----------
function explodeBoss(b,colors,text){const bx=b.x,by=b.y;burst(bx,by,30,{type:'shard',colors,speed:[150,420],size:[6,12],life:[.7,1.2],gravity:500});burst(bx,by,16,{type:'puff',colors:['#ffb020','#ff6a2a','#ffffff'],speed:[60,200],size:[12,22],life:[.5,.9],drag:2.5});rings.push({x:bx,y:by,max:150,life:0,dur:.6,color:'#fff',width:9});popup(bx,by-60,text,'#ffd23f',56);shake=Math.max(shake,22);flash=.6;flashColor='#fff';gameSound.effect('boom')}
const line=(x0,y0,x1,y1)=>{ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.stroke()};
function drawJaws(cx,cy,s,gap){ctx.save();ctx.translate(cx,cy);ctx.scale(s,s);ctx.lineJoin='round';ctx.strokeStyle=INK;ctx.lineWidth=4;const up=-gap*70,down=gap*62;ctx.fillStyle='#5a0a20';ctx.fillRect(-100,up,200,down-up);
 for(const [y,dir] of [[up,-1],[down,1]]){ctx.fillStyle='#fff';for(let i=0;i<8;i++){const tx=-90+i*25.7;ctx.beginPath();ctx.moveTo(tx-11,y);ctx.lineTo(tx,y-dir*20);ctx.lineTo(tx+11,y);ctx.closePath();ctx.fill();ctx.lineWidth=2;ctx.stroke()}
  const g=ctx.createLinearGradient(0,y,0,y+dir*90);g.addColorStop(0,'#9ae85a');g.addColorStop(1,'#3f8f1d');ctx.fillStyle=g;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-112,y);ctx.quadraticCurveTo(-100,y+dir*96,0,y+dir*100);ctx.quadraticCurveTo(100,y+dir*96,112,y);ctx.closePath();ctx.fill();ctx.stroke()}
 for(const sd of [-1,1]){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(sd*40,up-70,16,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=INK;ctx.beginPath();ctx.arc(sd*40,up-66,7,0,TAU);ctx.fill()}ctx.restore()}
function drawPie(px,py,rot){ctx.save();ctx.translate(px,py);ctx.rotate(rot);ctx.strokeStyle=INK;ctx.lineWidth=2.5;ctx.fillStyle='#d99a55';ctx.beginPath();ctx.ellipse(0,4,18,7,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(0,-1,16,8,0,Math.PI,TAU);ctx.quadraticCurveTo(10,4,0,3);ctx.quadraticCurveTo(-10,4,-16,-1);ctx.fill();ctx.stroke();ctx.fillStyle='#ff4d5e';ctx.beginPath();ctx.arc(0,-7,3.5,0,TAU);ctx.fill();ctx.restore()}
const FATALITIES={
 classic:{name:'BALLOON SLAM',pose(p,b,f){const bx=x*W,by=balloonY(),tx=b.x-bx,ty=b.y+70*b.scale-by;
   if(p<.42){const k=easeIn(p/.42);f.balloon={dx:tx*k,dy:ty*k}}else if(p<.62){f.balloon={dx:tx+rand(-3,3),dy:ty};f.pose={sx:1.25,sy:.72}}else{const k=easeOut(Math.min(1,(p-.62)/.25)),q=p-.62;f.balloon={dx:tx*(1-k),dy:ty*(1-k)};f.pose={dy:-q*900,rot:q*14,scale:Math.max(.1,1-q*1.6)}}
   f.at(.42,()=>{popup(b.x,b.y-30,'POW!','#ffd23f',66);shake=Math.max(shake,22);flash=.7;flashColor='#fff';burst(b.x,b.y+40,20,{type:'star',colors:['#ffd23f','#fff'],speed:[150,380],size:[5,9],life:[.4,.8]});rings.push({x:b.x,y:b.y+40,max:120,life:0,dur:.5,color:'#ffd23f',width:8});gameSound.effect('smash')});
   f.at(.88,()=>{burst(b.x,Math.max(20,b.y-200),40,{type:'confetti',colors:PARTY,speed:[100,360],size:[6,10],life:[.8,1.4],gravity:300});gameSound.effect('pop')})},
  draw(p,b,f){if(p>=.42||!f.balloon)return;const bx=x*W+f.balloon.dx,by=balloonY()+f.balloon.dy;ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=3;ctx.lineCap='round';for(let i=0;i<7;i++){const ox=(i-3)*9;line(bx+ox,by+40,bx+ox*1.5-f.balloon.dx*.3,by+40-f.balloon.dy*.5)}}},
 gumball:{name:'BUBBLE TRAP',pose(p,b,f){if(p>.42)f.pose={dy:-(p-.42)*320,rot:Math.sin(p*22)*.12,scale:.82};if(p>=.86)f.pose.alpha=0;f.at(.3,()=>gameSound.effect('boop'));
   f.at(.86,()=>{const y=b.y-(.86-.42)*320;burst(b.x,y,30,{type:'bubble',colors:['#ff9ad5','#ffffff','#ff7ac0'],speed:[100,320],size:[4,9],life:[.5,1]});popup(b.x,y,'POP!','#ff7ac0',62);shake=Math.max(shake,16);gameSound.effect('pop')})},
  draw(p,b,f){if(p>=.86)return;const bx=x*W,by=balloonY()-40,k=Math.min(1,p/.3),e=easeOut(k),cx=bx+(b.x-bx)*e,cy=by+(b.y-by)*e-(p>.42?(p-.42)*320:0),r=12+112*e*b.scale+Math.sin(p*30)*4;ctx.save();ctx.fillStyle='rgba(255,170,220,.32)';ctx.strokeStyle='#ff7ac0';ctx.lineWidth=5;ctx.beginPath();ctx.arc(cx,cy,r,0,TAU);ctx.fill();ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.85)';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.arc(cx,cy,r*.75,3.6,4.4);ctx.stroke();ctx.restore()}},
 clown:{name:'PIE PARTY',pose(p,b,f){if(p>.62){const q=p-.62;f.pose={dx:q*700,dy:-q*420,rot:q*12,scale:Math.max(.1,1-q)}}else if(p>.15)f.pose={dx:Math.sin(p*90)*3};
   [.15,.27,.39].forEach((th,i)=>f.at(th,()=>{burst(b.x+(i-1)*30*b.scale,b.y,14,{type:'puff',colors:['#ffffff','#fff3d6'],speed:[60,200],size:[6,12],life:[.5,.9]});popup(b.x,b.y-40-i*26,'SPLAT!','#ffffff',34);gameSound.effect('boop')}));
   f.at(.62,()=>{popup(b.x,b.y-50,'BOING!','#ff4d5e',58);shake=Math.max(shake,18);gameSound.effect('smash')});f.at(.9,()=>burst(Math.min(W-20,b.x+200),Math.max(20,b.y-120),36,{type:'confetti',colors:PARTY,speed:[100,320],size:[6,10],life:[.8,1.3],gravity:300}))},
  draw(p,b,f){const bx=x*W,by=balloonY()-20;
   [0,.12,.24].forEach((t0,i)=>{const k=(p-t0)/.15;if(k<0||k>1)return;const tx=b.x+(i-1)*30*b.scale,ty=b.y;drawPie(bx+(tx-bx)*k,by+(ty-by)*k-Math.sin(k*Math.PI)*90,k*7)});
   if(p<.62){const hits=[.15,.27,.39].filter(th=>p>=th).length;ctx.fillStyle='#fff';ctx.strokeStyle=INK;ctx.lineWidth=2;for(let i=0;i<hits;i++){const cx=b.x+(i-1)*30*b.scale,cy=b.y-8+i*8;ctx.beginPath();for(let k=0;k<7;k++){const a=k*TAU/7;ctx.arc(cx+Math.cos(a)*12,cy+Math.sin(a)*10,8,0,TAU)}ctx.fill()}}
   if(p>=.48&&p<.74){const k=Math.min(1,(p-.48)/.14),ex=bx+(b.x-bx)*k,ey=by+(b.y+40*b.scale-by)*k;ctx.strokeStyle=INK;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(bx,by);for(let i=1;i<=12;i++){const q=i/12;ctx.lineTo(bx+(ex-bx)*q+(i%2?8:-8),by+(ey-by)*q)}ctx.stroke();ctx.save();ctx.translate(ex,ey);ctx.fillStyle='#ff3b52';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,18,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#ff7a86';ctx.beginPath();ctx.ellipse(-6,-6,6,4,-.6,0,TAU);ctx.fill();ctx.restore()}}},
 toy:{name:'LASER EYES',pose(p,b,f){if(p>.1&&p<.72)f.pose={dx:Math.sin(p*120)*5,dy:Math.cos(p*97)*3,hurt:.5+.5*Math.sin(p*60)};if(p>=.72)f.pose={alpha:0};f.at(.1,()=>gameSound.effect('zap'));f.at(.4,()=>gameSound.effect('zap'));f.at(.72,()=>explodeBoss(b,['#9aa6bd','#5f6b85','#ffd23f','#ff8a2a'],'KABOOM!'))},
  draw(p,b,f){if(p<.1||p>=.72)return;const bx=x*W,by=balloonY();ctx.save();ctx.lineCap='round';for(const s of [-1,1]){const ex=bx+s*9,ey=by-13,tx=b.x+s*14+Math.sin(p*50+s)*8,ty=b.y-10;ctx.strokeStyle='rgba(95,240,255,.35)';ctx.lineWidth=18;line(ex,ey,tx,ty);ctx.strokeStyle='#5ff0ff';ctx.lineWidth=7;line(ex,ey,tx,ty);ctx.strokeStyle='#fff';ctx.lineWidth=2.5;line(ex,ey,tx,ty);glow(tx,ty,28,'#5ff0ff',.9)}ctx.restore();if(Math.random()<.5)burst(b.x+rand(-30,30),b.y+rand(-20,20),3,{colors:['#5ff0ff','#fff','#ffd23f'],speed:[80,220],life:[.2,.4]})}},
 melon:{name:'SEED STORM',pose(p,b,f){if(p>.08&&p<.68)f.pose={dx:Math.sin(p*110)*4,hurt:.3};if(p>=.68)f.pose={alpha:0};f.at(.68,()=>explodeBoss(b,['#ff5a7a','#3fbf55','#1b1240','#8be38f'],'SPLAT!'))},
  draw(p,b,f){if(p<.05||p>=.66)return;const bx=x*W,by=balloonY()-6;ctx.fillStyle=INK;for(let i=0;i<18;i++){const q=(p*7+i/18)%1,tx=b.x+(hash(i*3)-.5)*70*b.scale,ty=b.y+(hash(i*5)-.5)*50*b.scale;ctx.save();ctx.translate(bx+(tx-bx)*q,by+(ty-by)*q);ctx.rotate(Math.atan2(ty-by,tx-bx)+Math.PI/2);ctx.beginPath();ctx.ellipse(0,0,2.6,4.4,0,0,TAU);ctx.fill();ctx.restore()}if(Math.random()<.6)burst(b.x+rand(-40,40)*b.scale,b.y+rand(-30,30)*b.scale,2,{type:'puff',colors:['#ff5a7a','#ff8aa0'],speed:[30,90],size:[3,6],life:[.3,.5]})}},
 monster:{name:'MEGA CHOMP',pose(p,b,f){if(p>=.46)f.pose={alpha:0};f.at(.46,()=>{popup(b.x,b.y-110,'CHOMP!','#7ad83f',62);shake=Math.max(shake,22);gameSound.effect('smash')});f.at(.72,()=>{popup(b.x,b.y-100,'BURP!','#b6ff7a',44);gameSound.effect('boop')})},
  draw(p,b,f){if(p<.04||p>.97)return;const appear=Math.min(1,(p-.04)/.2),leave=p>.85?1-(p-.85)/.12:1,s=b.scale*1.35*Math.max(0,backOut(appear))*Math.max(0,leave),gap=p<.4?1:p<.46?1-(p-.4)/.06:.08+.06*Math.sin(p*60);if(s>.02)drawJaws(b.x,b.y,s,gap)}},
 ninja:{name:'SHADOW SLASH',pose(p,b,f){const pts=[[-1,-.6],[1,-.2],[-1,.5],[1,.8]],bx=x*W,by=balloonY();if(p>=.15&&p<.7){const i=Math.min(3,Math.floor((p-.15)/.1)),[sx,sy]=pts[i];f.balloon={dx:b.x+sx*95*b.scale-bx,dy:b.y+sy*70*b.scale-by}}else if(p>=.7&&p<.85){const k=(p-.7)/.15,[sx,sy]=pts[3];f.balloon={dx:(b.x+sx*95*b.scale-bx)*(1-k),dy:(b.y+sy*70*b.scale-by)*(1-k)}}
   if(p>=.7)f.pose={split:Math.min(1,(p-.7)/.3)};[.2,.3,.4,.5].forEach(th=>f.at(th,()=>gameSound.effect('close')));f.at(.7,()=>{popup(b.x,b.y-100,'SLASH!','#ffffff',58);flash=.6;flashColor='#fff';shake=Math.max(shake,16);gameSound.effect('smash')})},
  draw(p,b,f){const dark=p<.15?p/.15:p<.7?1:Math.max(0,1-(p-.7)/.2);ctx.fillStyle=`rgba(5,0,20,${dark*.55})`;ctx.fillRect(-OX-40,-40,SW+80,H+80);
   [-.5,.6,-.15,1.15].forEach((a,i)=>{const t0=.2+i*.1;if(p<t0||p>.72)return;const k=Math.min(1,(p-t0)/.05),L=150*b.scale;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(a);ctx.lineCap='round';ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=12;line(-L,0,-L+2*L*k,0);ctx.strokeStyle='#fff';ctx.lineWidth=4;line(-L,0,-L+2*L*k,0);ctx.restore()})}},
 galaxy:{name:'BLACK HOLE',pose(p,b,f){if(p>.2){const q=Math.min(1,(p-.2)/.65);f.pose={rot:q*q*18,scale:Math.max(0,1-q**1.4),dx:Math.sin(q*12)*30*(1-q),dy:Math.cos(q*12)*20*(1-q)}}f.at(.05,()=>gameSound.effect('zap'));
   f.at(.86,()=>{flash=.8;flashColor='#e6d6ff';popup(b.x,b.y-70,'GONE!','#c9a8ff',58);shake=Math.max(shake,14);gameSound.effect('boom');burst(b.x,b.y,30,{type:'star',colors:['#fff','#c9a8ff','#5ff0ff'],speed:[150,400],size:[4,8],life:[.5,1]})})},
  under(p,b,f){if(p<.05||p>.97)return;const r=72*b.scale*easeOut(Math.min(1,(p-.05)/.2))*Math.max(0,p>.86?1-(p-.86)/.11:1);ctx.save();ctx.translate(b.x,b.y);for(let i=0;i<5;i++){ctx.save();ctx.rotate(p*20+i);ctx.strokeStyle=['#7a3cff','#5ff0ff','#ff7ad9','#c9a8ff','#2a6bff'][i];ctx.globalAlpha=.75;ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(0,0,r*(1.3+i*.15),r*(.5+i*.06),0,0,Math.PI*1.4);ctx.stroke();ctx.restore()}
   const g=ctx.createRadialGradient(0,0,0,0,0,r+1);g.addColorStop(0,'#000');g.addColorStop(.7,'#05001a');g.addColorStop(1,'rgba(122,60,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r+1,0,TAU);ctx.fill();ctx.fillStyle='#fff';for(let i=0;i<14;i++){const q=1-((p*3+i/14)%1),a=i*2.4+p*6,d=r*1.2+q*160;star(Math.cos(a)*d,Math.sin(a)*d,3,1.2,4);ctx.fill()}ctx.restore()}},
 gold:{name:'MIDAS TOUCH',pose(p,b,f){f.pose={gold:clamp((p-.08)/.3,0,1),dx:p<.4?Math.sin(p*80)*2:0};if(p>=.72)f.pose.alpha=0;f.at(.06,()=>gameSound.effect('charged'));
   f.at(.72,()=>{burst(b.x,b.y,44,{type:'shard',colors:['#ffd23f','#ffe680','#c98a00'],speed:[150,420],size:[6,12],life:[.8,1.3],gravity:500});burst(b.x,b.y,18,{type:'star',colors:['#fff','#ffe680'],speed:[100,300],size:[5,9],life:[.5,1]});popup(b.x,b.y-70,'SHATTER!','#ffd23f',56);shake=Math.max(shake,20);flash=.5;flashColor='#ffe680';gameSound.effect('boom')})},
  draw(p,b,f){const bx=x*W,by=balloonY()-52;if(p>.05&&p<.42){const w=14+Math.sin(p*60)*3;ctx.save();ctx.lineCap='round';ctx.strokeStyle='rgba(255,210,63,.4)';ctx.lineWidth=w*2.2;line(bx,by,b.x,b.y);ctx.strokeStyle='#ffe680';ctx.lineWidth=w;line(bx,by,b.x,b.y);ctx.strokeStyle='#fff';ctx.lineWidth=w*.3;line(bx,by,b.x,b.y);ctx.fillStyle='#fff';for(let i=0;i<5;i++){const q=(p*4+i/5)%1;star(bx+(b.x-bx)*q+Math.sin(i*3)*10,by+(b.y-by)*q,5,2,4);ctx.fill()}ctx.restore()}
   if(p>=.45&&p<.72){const k=(p-.45)/.27;ctx.save();ctx.strokeStyle=INK;ctx.lineWidth=3;for(let i=0;i<5;i++){let cx=b.x,cy=b.y;ctx.beginPath();ctx.moveTo(cx,cy);const a=i*1.26+.3;for(let j=1;j<=4&&j/4<=k+.01;j++){cx+=Math.cos(a+(j%2?.4:-.4))*24*b.scale;cy+=Math.sin(a+(j%2?.4:-.4))*24*b.scale;ctx.lineTo(cx,cy)}ctx.stroke()}ctx.restore()}}}};
